import { useState } from 'react';

type BuyType = 'fractional' | 'unit100';

export default function App() {
  const [stockCode, setStockCode] = useState('');
    const [stockName, setStockName] = useState('');
      const [price, setPrice] = useState('');
        const [high, setHigh] = useState('');
          const [ma25, setMa25] = useState('');
            const [volume, setVolume] = useState('');
              const [buyType, setBuyType] = useState<BuyType>('fractional');
                const [afterRally, setAfterRally] = useState(false);
                  const [noStopLoss, setNoStopLoss] = useState(true);
                    const [fomo, setFomo] = useState(false);

                      const n = (v: string) => Number(v) || 0;

                        const current = n(price);
                          const recentHigh = n(high);
                            const line25 = n(ma25);
                              const vol = n(volume);

                                let score = 50;
                                  const plus: string[] = [];
                                    const minus: string[] = [];
                                      const warnings: string[] = [];

                                        if (current > 0 && line25 > 0) {
                                            if (current >= line25) {
                                                  score += 15;
                                                        plus.push('現在値が25日線以上：トレンドは強め');
                                                            } else {
                                                                  score -= 10;
                                                                        minus.push('現在値が25日線未満：弱さあり');
                                                                            }
                                                                              }

                                                                                if (current > 0 && recentHigh > current) {
                                                                                    const rate = ((recentHigh - current) / recentHigh) * 100;

                                                                                        if (rate >= 3 && rate <= 10) {
                                                                                              score += 15;
                                                                                                    plus.push(`直近高値から約${rate.toFixed(1)}%下落：押し目候補`);
                                                                                                        } else if (rate > 15) {
                                                                                                              score -= 10;
                                                                                                                    minus.push(`直近高値から約${rate.toFixed(1)}%下落：下落が深い`);
                                                                                                                        } else {
                                                                                                                              minus.push(`直近高値から約${rate.toFixed(1)}%下落：押し目として浅い`);
                                                                                                                                  }
                                                                                                                                    }

                                                                                                                                      if (vol >= 1 && vol <= 2.5) {
                                                                                                                                          score += 10;
                                                                                                                                              plus.push('出来高倍率が適度：注目度あり');
                                                                                                                                                } else if (vol > 3) {
                                                                                                                                                    score -= 5;
                                                                                                                                                        minus.push('出来高倍率が高すぎる：過熱注意');
                                                                                                                                                          }

                                                                                                                                                            if (buyType === 'fractional') {
                                                                                                                                                                score += 5;
                                                                                                                                                                    plus.push('単元未満株：少額で確認しやすい');
                                                                                                                                                                      } else {
                                                                                                                                                                          minus.push('100株購入：失敗時のダメージが大きい');
                                                                                                                                                                            }

                                                                                                                                                                              if (afterRally) {
                                                                                                                                                                                  score -= 10;
                                                                                                                                                                                      minus.push('急騰後：高値掴みリスク');
                                                                                                                                                                                        }

                                                                                                                                                                                          if (noStopLoss) {
                                                                                                                                                                                              score -= 15;
                                                                                                                                                                                                  minus.push('損切りライン未設定：出口がない');
                                                                                                                                                                                                    } else {
                                                                                                                                                                                                        score += 10;
                                                                                                                                                                                                            plus.push('損切りラインあり：リスク管理あり');
                                                                                                                                                                                                              }

                                                                                                                                                                                                                if (fomo) {
                                                                                                                                                                                                                    score -= 15;
                                                                                                                                                                                                                        minus.push('FOMO・焦りあり：感情買い注意');
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                            if (buyType === 'unit100' && fomo) {
                                                                                                                                                                                                                                warnings.push('100株かつFOMOありです。成行ではなく、指値・損切りライン・許容損失額を確認してください。');
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                    if (buyType === 'unit100' && noStopLoss) {
                                                                                                                                                                                                                                        warnings.push('100株で損切りライン未設定です。買う前に、いくらまで下がったら撤退するかを決めてください。');
                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                            score = Math.max(0, Math.min(100, score));

                                                                                                                                                                                                                                              const rank =
                                                                                                                                                                                                                                                  score >= 80 ? '強い買い候補' :
                                                                                                                                                                                                                                                      score >= 65 ? '買い候補' :
                                                                                                                                                                                                                                                          score >= 50 ? '監視' :
                                                                                                                                                                                                                                                              score >= 35 ? '見送り寄り' :
                                                                                                                                                                                                                                                                  '冷却タイム';

                                                                                                                                                                                                                                                                    const title = stockName || stockCode || '未入力の銘柄';

                                                                                                                                                                                                                                                                      const nextAction =
                                                                                                                                                                                                                                                                          warnings.length > 0 ? '注意項目を確認してから、買う数量と注文方法を決めてください。' :
                                                                                                                                                                                                                                                                              score >= 80 ? '損切りラインと利確目安を確認してから、指値で検討してください。' :
                                                                                                                                                                                                                                                                                  score >= 65 ? '買い候補です。押し目・出来高・地合いをもう一度確認してください。' :
                                                                                                                                                                                                                                                                                      score >= 50 ? '監視継続です。条件が整うまで待つのが無難です。' :
                                                                                                                                                                                                                                                                                          '一旦待ちです。時間を置いて再チェックしてください。';

                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <main style={{ padding: 20, fontFamily: 'system-ui', maxWidth: 640, margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                      <h1>日本株 買う前チェッカー</h1>
                                                                                                                                                                                                                                                                                                            <p>買う前に、いったん冷静になるためのセルフチェックです。</p>

                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'grid', gap: 10 }}>
                                                                                                                                                                                                                                                                                                                          <input placeholder="銘柄コード 例：9434" value={stockCode} onChange={(e) => setStockCode(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                  <input placeholder="銘柄名 例：ソフトバンク" value={stockName} onChange={(e) => setStockName(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                          <input placeholder="現在値" value={price} onChange={(e) => setPrice(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                  <input placeholder="直近高値" value={high} onChange={(e) => setHigh(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                          <input placeholder="25日線" value={ma25} onChange={(e) => setMa25(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                  <input placeholder="出来高倍率 例：1.5" value={volume} onChange={(e) => setVolume(e.target.value)} />

                                                                                                                                                                                                                                                                                                                                                                          <select value={buyType} onChange={(e) => setBuyType(e.target.value as BuyType)}>
                                                                                                                                                                                                                                                                                                                                                                                    <option value="fractional">単元未満株</option>
                                                                                                                                                                                                                                                                                                                                                                                              <option value="unit100">100株（単元株）</option>
                                                                                                                                                                                                                                                                                                                                                                                                      </select>

                                                                                                                                                                                                                                                                                                                                                                                                              <label>
                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="checkbox" checked={afterRally} onChange={(e) => setAfterRally(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                  急騰後
                                                                                                                                                                                                                                                                                                                                                                                                                                          </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" checked={noStopLoss} onChange={(e) => setNoStopLoss(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      損切りライン未設定
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="checkbox" checked={fomo} onChange={(e) => setFomo(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          FOMO・焦っている
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section style={{ marginTop: 20, padding: 16, border: '1px solid #ddd', borderRadius: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>チェック結果</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ fontWeight: 700 }}>{title}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 36, fontWeight: 800 }}>{score} / 100</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 24, fontWeight: 800 }}>{rank}</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {warnings.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ marginTop: 14, padding: 12, border: '1px solid #f5c542', borderRadius: 10, background: '#fff8db' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>注意</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {warnings.map((x) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li key={x}>{x}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>次に確認すること</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{nextAction}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>加点理由</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {plus.map((x) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={x}>{x}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>確認すべきリスク</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {minus.map((x) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li key={x}>{x}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: 13, color: '#666' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    これは売買推奨ではなく、参考情報です。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }